### ISSUE TITLE
"Jellyfin Recently Added Scan" doesn't add latest episodes but "Jellyfin Full Library Scan" does

### ISSUE THREAD

**Issue by canoziia** [seerr-team/seerr#177] opened 2022-07-06 07:29 UTC
### Description

"Jellyfin Recently Added Scan" doesn't add latest episodes but "Jellyfin Full Library Scan" does

### Version

Jellyseerr:1.1.1    Jellyfin:10.8.1

### Steps to Reproduce

1. request a serie on jellyseerr
2. new episodes have been added to jellyfin
3. jellyseerr runs "Jellyfin Recently Added Scan"
4. result: jellyseerr doesn't add latest episodes

### Platform

desktop

### Device

lenovo PC

### Operating System

windows 11

### Browser

Chrome

### Additional Context

I tracked "Recently Added" items from the jellyfin api, all items are still in there until [this line](https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/job/jellyfinsync/index.ts#L486) filters out items with item.Type==="Episode".
if change `} else if (item.Type === 'Series') {` to `} else if (item.Type === 'Series' || item.Type === 'Episode') {`, it works fine.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment] 2022-07-08 02:09
There is a planned upcoming episode feature which will add this functionality

**Comment by canoziia** [comment] 2022-07-15 01:43
> There is a planned upcoming episode feature which will add this functionality

Thanks!

**Comment by zeroquinc** [comment] 2022-07-28 13:39
This also happens with movies. The recently added scan in Jellyseerr doesn't pick up the new movie, but a Full Library Scan does.

**Comment by Fallenbagel** [comment] 2022-07-29 16:08
> This also happens with movies. The recently added scan in Jellyseerr doesn't pick up the new movie, but a Full Library Scan does.

What's weird is I cannot reproduce this. I have jellyseerr running and everytime i add a movie or show, it gets picked up right away (through a recently added scan) 🤔

**Comment by zeroquinc** [comment] 2022-07-29 17:34
> > This also happens with movies. The recently added scan in Jellyseerr doesn't pick up the new movie, but a Full Library Scan does.
> 
> What's weird is I cannot reproduce this. I have jellyseerr running and everytime i add a movie or show, it gets picked up right away (through a recently added scan) 🤔

Ah that's a bummer, well I'm glad it works for you tho. So it's probably a config thingy. In Overseerr it works correctly tho. I have Discord notifications set up and Overseerr is instantly, but with Jellyseerr I have to wait on the hourly full scan for me to get the notification. Also checked the UI but it marks it as available after I manually press Full Scan.

**Comment by Fallenbagel** [comment] 2022-07-29 20:49
Have you tried to purge the config and try the `develop` tag too

**Comment by zeroquinc** [comment] 2022-07-30 02:37
> 

Just did exactly what you said but sadly didn't fix it for me. I haven't pressed a manual scan once, it sees my current library but after a request and the 5m wait for a Recently Added Scan it doesn't pick up the movie.

**Comment by canoziia** [comment] 2022-07-30 04:52
> > Have you tried to purge the config+container and recreate and then try the `develop` tag. (For testing purposes I recommend not running a full scan when you first setup on develop tag and then do an aggressive recently added scan)
> 
> Just did exactly what you said but sadly didn't fix it for me. I haven't pressed a manual scan once, it sees my current library but after a request and the 5m wait for a Recently Added Scan it doesn't pick up the movie.

You can try to print var `item` at [/server/job/jellyfinsync/index.ts#L483](https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/job/jellyfinsync/index.ts#L483) and [/server/job/jellyfinsync/index.ts#L485](https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/job/jellyfinsync/index.ts#L485) and see if there is a difference between them.

**Comment by zeroquinc** [comment] 2022-07-30 15:09
> > > Have you tried to purge the config+container and recreate and then try the `develop` tag. (For testing purposes I recommend not running a full scan when you first setup on develop tag and then do an aggressive recently added scan)
> > 
> > 
> > Just did exactly what you said but sadly didn't fix it for me. I haven't pressed a manual scan once, it sees my current library but after a request and the 5m wait for a Recently Added Scan it doesn't pick up the movie.
> 
> You can try to print var `item` at [/server/job/jellyfinsync/index.ts#L483](https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/job/jellyfinsync/index.ts#L483) and [/server/job/jellyfinsync/index.ts#L485](https://github.com/Fallenbagel/jellyseerr/blob/4f972be8584e48f544268aef9d1d05769ba2e38e/server/job/jellyfinsync/index.ts#L485) and see if there is a difference between them.

I don't know what you mean by that sadly

**Comment by zeroquinc** [comment] 2022-08-02 08:59
Any updates on this? it still happens. it runs a manual scan every day at 3AM and thats the only moment Jellyseer recognizes the media. While Jellyfin itself notices it right away.

![Discord_SYuL2BcaJk](https://user-images.githubusercontent.com/39315068/182335751-f8b11fbb-4e9d-4ca1-9184-6d4605a416ac.png)

**Comment by Fallenbagel** [comment] 2022-08-03 09:38
@zeroquinc it was the metadata date problem?

**Comment by zeroquinc** [comment] 2022-08-03 23:01
@Fallenbagel Yes, since I changed the Jellyfin setting `Date added behavior for new content` to `Use data scanned into library` the issue is solved. The metadata for `Date added` was wrong for all movies. I manually fixed my existing movies since I don't have a huge library and my new movies are getting the right metadata now.

**Comment by Fallenbagel** [comment] 2022-08-04 12:55
Alright I'm closing this issue then c;
Glad you worked it out!

**Closed** 2022-08-04 12:55 UTC
Labels: support

**Comment by vasilvestre** [comment] 2026-09-01 10:49
> [@fallenbagel](https://github.com/fallenbagel) Yes, since I changed the Jellyfin setting `Date added behavior for new content` to `Use data scanned into library` the issue is solved. The metadata for `Date added` in Jellyfin was wrong for all movies. I manually fixed my existing movies since I don't have a huge library and my new movies are getting the right metadata now. I also fixed the issue that my newest movies didn't got categorized in the `Latest movies` section in Jellyfin, which probably is the category that Jellyseerr scans when running a `Recently added scan`.

I also enabled this option, Jellyfin display my series in recently added.

<img width="269" height="383" alt="Image" src="https://github.com/user-attachments/assets/d0da6366-03c7-443b-90ac-1c8b3a2228d0" />

<img width="807" height="132" alt="Image" src="https://github.com/user-attachments/assets/d511e280-fcfd-45cd-95e2-5f058593d615" />

I've run the task to analyse new content manually (it runs every minute or so anyway) and it's still unavailable. A full scan works.

Seerr : 3.4.1
Jellyfin : 10.11.11

Edit :

<img width="1313" height="262" alt="Image" src="https://github.com/user-attachments/assets/0c5a014e-b2bb-465b-81f5-83eeee54808e" />

Sadly, I don't have more info than that except the 404. The full scan works.

**Comment by fallenbagel** [comment] 2026-09-01 11:06
> > [@fallenbagel](https://github.com/fallenbagel) Yes, since I changed the Jellyfin setting `Date added behavior for new content` to `Use data scanned into library` the issue is solved. The metadata for `Date added` in Jellyfin was wrong for all movies. I manually fixed my existing movies since I don't have a huge library and my new movies are getting the right metadata now. I also fixed the issue that my newest movies didn't got categorized in the `Latest movies` section in Jellyfin, which probably is the category that Jellyseerr scans when running a `Recently added scan`.
> 
> I also enabled this option, Jellyfin display my series in recently added.
> 
> <img width="269" height="383" alt="Image" src="https://github.com/user-attachments/assets/d0da6366-03c7-443b-90ac-1c8b3a2228d0" />
> 
> <img width="807" height="132" alt="Image" src="https://github.com/user-attachments/assets/d511e280-fcfd-45cd-95e2-5f058593d615" />
> 
> I've run the task to analyse new content manually (it runs every minute or so anyway) and it's still unavailable. A full scan works.
> 
> Seerr : 3.4.1
> Jellyfin : 10.11.11
> 
> Edit :
> 
> <img width="1313" height="262" alt="Image" src="https://github.com/user-attachments/assets/0c5a014e-b2bb-465b-81f5-83eeee54808e" />
> 
> Sadly, I don't have more info than that except the 404. The full scan works.

Your issue is not related nor a bug at all. The 404 is due to youe jellyfinUserId of your owner account having changed. Just follow the docs:
https://docs.seerr.dev/troubleshooting/#account-does-not-have-admin-privileges
And then you'll have it updating.

Please use the proper support channel for support queries.
